/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/t_shirt_hoodie_3d_model.glb
Source: https://sketchfab.com/3d-models/t-shirt-hoodie-3d-model-fd8d10eb5f5748e581ca6bd0db2abcce
Title: t shirt hoodie 3d model
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export default function Hoodie({ color }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/t_shirt_hoodie_3d_model.glb");

  useEffect(() => {
    if (materials["Material.001"]) {
      materials["Material.001"].color.set(color);
    }
  }, [color, materials]);


  return (
    <group
      ref={group}
      scale={0.06}
      rotation={[1.5, 0, -0.5]}
      position={[0, 0, 0]}
    >
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/t_shirt_hoodie_3d_model.glb");
